#! /bin/sh

sxhkd &

bspc monitor LVDS-1 -d 01 02 03
bspc monitor VGA-1  -d M2

bspc config border_width         3
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config click_to_focus        true

bspc rule -a URxvt:floating 	state=floating
bspc rule -a Kupfer.py 		focus=on

xsetroot -cursor_name left_ptr
